---

#- hosts: seed-hosts
#  roles:
#  - ../../galaxy/openshift-ansible-contrib/roles/openshift-pv-cleanup

- vars_prompt:
    name: "delete_cluster"
    prompt: "Are you sure you want to delete the {{env_id}} cluster ] (yes/no)"
    private: no
  pre_tasks:
      - name: "setting the delete_cluster fact"
        set_fact:
          delete_cluster: "{{ delete_cluster }}"
      - name: "setting up the fail module catch"
        fail:
          msg: "Abort task: delete {{env_id}} cluster"
        when: delete_cluster == false


- import_playbook: openstack/delete.yml
  when:
  - hosting_infrastructure == 'openstack'

- import_playbook: aws/delete.yml
  when:
  - hosting_infrastructure == 'aws'

- import_playbook: gcp/delete.yml
  when:
  - hosting_infrastructure == 'gcp'
