---

- hosts: localhost
  tasks:
  - pause:
      prompt: "Are you sure you want to delete the {{env_id}} cluster (yes/no)"
    register: delete_cluster
  # pre_tasks:
  - name: "setting the delete_cluster fact"
    set_fact:
      delete_cluster: "{{ delete_cluster }}"
  - name: "Error out unless user confirms deletion of cluster"
    fail:
      msg: "Abort task: delete {{env_id}} cluster"
    when:
      - delete_cluster | default('no') | bool
